<?php
/******************************************
* @Created on APL 20, 2014
* @Package: kisansanchar
* @Developer: Praveen Singh
* @URL : http://kisansanchar.com/
*******************************************/

$basedir=dirname(__FILE__)."";
include_once $basedir."/include/actionHeader.php";

checkSession(false,2);

if(empty($_SESSION['joiningData'])){
	header('Location: ' . $_SERVER['HTTP_REFERER']);
	exit;
}

$headerColumns = $headingcsv = $rows = array();
$headingcsv[]  = 'CCAFS Project analysis report prepared by Kisan Sanchar downloaded on '.date('d M Y , h:i:s A');
$headingexcel  = 'CCAFS Project analysis report prepared by Kisan Sanchar downloaded on '.date('d M Y , h:i:s A');

$footer    = array("Generated by :","".URL_SITE."");

if(!empty($_SESSION['joiningData'])){

	$date = array("Generated On :","".date('D M d H:i:s Y').""); ;

	if(isset($_GET['type']) && $_GET['type']=='csv') {

		$filename = 'kisan_sanchar_analysis_csv_report_'.date('d-m-Y-A');

		header('Content-Type: text/csv; charset=utf-8');
		header('Content-Disposition: attachment; filename='.$filename.'.csv');

		// create a file pointer connected to the output stream
		$output = fopen('php://output', 'w');		

		fputcsv($output, $headingcsv); //output the Title

		fputcsv($output, array('id'=>'')); //output line break

		if(!empty($_SESSION['joiningData'])){?>

			<?php foreach($_SESSION['joiningData'] as $keymobile => $kisanValueAlloneAll){ ?>
					
					<?php fputcsv($output, array('Mobile Number : '.$keymobile.'')); //output the Title ?>								    
					<?php foreach($kisanValueAlloneAll as $keyStatus => $kisanValueAll){?>

					<?php fputcsv($output, array('Status : '.$keyStatus.'')); //output the Title ?>
					
					<?php if(isset($kisanValueAll[0])){?>
						<?php foreach($kisanValueAll[0] as $keyField => $fieldValue){ ?>
							<?php $headerColumns[] = str_replace("_"," ",$keyField);?>
						<?php } ?>
						<?php fputcsv($output, $headerColumns); //output the Title ?>
					<?php } ?>					
														
					<?php foreach($kisanValueAll as $resultkey => $resultTD){ ?>
						<?php $rows = array();?>
						<?php foreach($resultTD as $tdkey => $resultTDvalue){ ?>
							<?php $rows[] = $resultTDvalue;?>
						<?php } ?>
						<?php fputcsv($output, $rows);?>
					<?php } ?>		

				<?php } ?>				

			<?php } ?>

		 <?php } ?>

		<?php fputcsv($output, array('id'=>'')); //output line break ?>

		<?php fputcsv($output, $footer); //output the Footer ?>
		
		<?php fputcsv($output, array('id'=>'')); //output line break ?>

		<?php fputcsv($output, $date); ?> 

	<?php } else {

		$filename = 'kisan_sanchar_analysis_excel_report_'.date('d-m-Y-A');

		header("Content-type: application/vnd.ms-excel");
		header("Content-Disposition: attachment;Filename=".$filename.".xls");
		
		echo "<html>";
		echo "<body>";

		echo "<table border='0'>";

		echo "<tr>";
		echo "<th align='left' colspan='17'>".$headingexcel."</th>";
		echo "</tr>";

		echo "<tr>";
		echo "<td align='left' colspan='17'>&nbsp;</td>";
		echo "</tr>";

		echo "</table>";

		echo "<table border='1'>";	
		
		if(!empty($_SESSION['joiningData'])){

			foreach($_SESSION['joiningData'] as $keymobile => $kisanValueAlloneAll){

				$farmerData = $adminObj->SelectFarmerDetail($keymobile);	

				echo "<tr>";
				echo "<th align='left' style='background:#EBEBEB;' colspan='2'>Mobile Number : ".$keymobile."</th>";
				if(!empty($farmerData)){

					echo "<th align='left' style='background:#EBEBEB;' colspan='4'>";
						if(isset($farmerData['pfirstname'])){
							echo stripslashes($farmerData['pfirstname']);						
						}
						if(isset($farmerData['plastname'])){
							echo '&nbsp;'.trim(stripslashes($farmerData['plastname']));
						}
						if(isset($farmerData['gender']) && $farmerData['gender']=='M' ){
							echo ', S/o ';
						} else {
							echo ', D/o ';
						}
						if(!empty($farmerData['pfathername'])){
							echo stripslashes($farmerData['pfathername']);
						} else if(!empty($farmerData['sfathername'])){
							echo stripslashes($farmerData['sfathername']);
						} else {
							echo '----';
						}
					echo "</th>";

					echo "<th align='left' style='background:#EBEBEB;' colspan='10'>";
						if(isset($farmerData['village'])){
							echo stripslashes($farmerData['village']);
						}
						if(isset($farmerData['district'])){
							echo ', '.stripslashes($farmerData['district']);
						}
						if(isset($farmerData['state'])){
							echo ', '.stripslashes($farmerData['state']);
						}
					echo "</th>";
				}
				echo "</tr>";
				
				echo "<tr>";
				echo "<td align='left' colspan='16'>&nbsp;</td>";
				echo "</tr>";
								    
				foreach($kisanValueAlloneAll as $keyStatus => $kisanValueAll){

					echo "<tr>";
					echo "<th align='left'>Status : ".$keyStatus."</th>";
					echo "</tr>";
					
					if(isset($kisanValueAll[0])){
						echo "<tr>";
						foreach($kisanValueAll[0] as $keyField => $fieldValue){
							echo "<th align='left'>".str_replace("_"," ",$keyField)."</th>";
						}	
						echo "</tr>";
					}					
														
					foreach($kisanValueAll as $resultkey => $resultTD){
						echo "<tr>";
						foreach($resultTD as $tdkey => $resultTDvalue){
							echo "<td align='left'>".$resultTDvalue."</td>";
						} 
						echo "</tr>";
					}
				}

				echo "<tr>";
				echo "<td align='left' colspan='16'>&nbsp;</td>";
				echo "</tr>";
			}
		 }

		echo "</table>";

		echo "<table border='0'>";

		echo "<tr>";echo "</tr>";

		echo "<tr>";
		foreach($footer as $footervalue){
		echo "<td>".$footervalue."</td>";
		}		

		echo "<tr>";
		foreach($date as $textdate){
		echo "<td>".$textdate."</td>";
		}	
		echo "</tr>";

		echo "</table>";
		echo "</body>";
		echo "</html>";
	}
}
?>