<?php
/******************************************
* @Created on APL 20, 2014
* @Package: kisansanchar
* @Developer: Praveen Singh
* @URL : http://kisansanchar.com/
*******************************************/

$basedir=dirname(__FILE__)."";
include_once $basedir."/include/actionHeader.php";

checkSession(false,2);

if(empty($_SESSION['resultData'][1])){
	header('Location: ' . $_SERVER['HTTP_REFERER']);
	exit;
}

$headerColumns = $headingcsv = $rows = array();
$headingcsv[]  = 'Kisan Sancher analysis report downloaded on '.date('d M Y h:i:s A');
$headingexcel  = 'Kisan Sancher analysis report downloaded on '.date('d M Y h:i:s A');

$footer    = array("Generated by :","".URL_SITE."");

if(!empty($_SESSION['resultData'][1])){

	$firstRow = $_SESSION['resultData'][1];
	
	foreach($firstRow as $keyField => $fieldValue){
		$headerColumns[] = str_replace("_"," ",$keyField);
	}

	$date = array("Generated On :","".date('D M d H:i:s Y').""); ;

	if(isset($_GET['type']) && $_GET['type']=='csv') {

		$filename = 'kisan_sanchar_analysis_csv_report_'.date('d-m-Y-A');

		header('Content-Type: text/csv; charset=utf-8');
		header('Content-Disposition: attachment; filename='.$filename.'.csv');

		// create a file pointer connected to the output stream
		$output = fopen('php://output', 'w');		

		fputcsv($output, $headingcsv); //output the Title

		fputcsv($output, array('id'=>'')); //output line break

		fputcsv($output, $headerColumns); //output the Title		

		foreach($_SESSION['resultData'] as $resultkey => $resultTD){
			$rows = array();
			foreach($resultTD as $tdkey => $resultTDvalue){
				$rows[] = $resultTDvalue;
			}
			fputcsv($output, $rows);
		} 
		
		fputcsv($output, array('id'=>'')); //output line break

		fputcsv($output, $footer); //output the Footer	
		
		fputcsv($output, array('id'=>'')); //output line break

		fputcsv($output, $date);

	} else {

		$filename = 'kisan_sanchar_analysis_excel_report_'.date('d-m-Y-A');

		header("Content-type: application/vnd.ms-excel");
		header("Content-Disposition: attachment;Filename=".$filename.".xls");
		
		echo "<html>";
		echo "<body>";

		echo "<table border='0'>";

		echo "<tr>";
		echo "<th colspan='10'>".$headingexcel."</th>";
		echo "</tr>";

		echo "</table>";

		echo "<table border='1'>";		

		echo "<tr>";
		foreach($firstRow as $keyField => $fieldValue){
		echo "<th>".ucwords(str_replace("_"," ",$keyField))."</th>";
		}	
		echo "</tr>";

		foreach($_SESSION['resultData'] as $resultkey => $resultTD){
			echo "<tr>";
			foreach($resultTD as $tdkey => $resultTDvalue){
				echo "<td align='left'>".$resultTDvalue."</td>";
			}
			echo "</tr>";
		}

		echo "</table>";

		echo "<table border='0'>";

		echo "<tr>";echo "</tr>";

		echo "<tr>";
		foreach($footer as $footervalue){
		echo "<td>".$footervalue."</td>";
		}		

		echo "<tr>";
		foreach($date as $textdate){
		echo "<td>".$textdate."</td>";
		}	
		echo "</tr>";

		echo "</table>";
		echo "</body>";
		echo "</html>";
	}
}
?>